# collections

- Python的模組，這個模組實作了一些特別的容器資料型態，用來替代 Python 一般內建的容器。

>實作項目  |  說明
>------------- | -------------
>namedtuple() | 用來建立具名欄位的 tuple 子類別的工廠函式
>deque | 一個類似 list 的容器，可以快速的在頭尾加入 (append) 元素與移除 (pop) 元素 
>ChainMap | 一個類似 dict 的類別，用來為多個對映 (mapping) 建立單一的視圖 (view)
>Counter | dict 的子類別，用來計算可雜湊物件的數量
>OrderedDict | dict 的子類別，會記錄物件被加入的順序
>defaultdict | dict 的子類別，當值不存在 dict 中時會呼叫一個提供預設值的工廠函式
>UserDict | dict 物件的包裝器 (wrapper)，簡化了 dict 的子類別化過程
>UserList | list 物件的包裝器，簡化了 list 的子類別化過程
>UserString | 字串物件的包裝器，簡化了字串的子類別化過程

1. defaultdict

>- defaultdict是字典的一種變體，它可以自動為字典提供默認值。

In [1]:
from collections import defaultdict
# 建立一個 defaultdict，預設值為 0
count = defaultdict(int)
print(type(count))  # <class 'collections.defaultdict'>
words = ['AAA', 'BBB', 'CCC', 'DDD', 'EEE', 'FFF']
print(type(words))  # <class 'list'>
for word in words:
    count[word] += 1
#
print(count)


<class 'collections.defaultdict'>
<class 'list'>
defaultdict(<class 'int'>, {'AAA': 1, 'BBB': 1, 'CCC': 1, 'DDD': 1, 'EEE': 1, 'FFF': 1})


2. OrderedDict

>- OrderedDict是字典的一種變體，它記住了元素插入的順序。

In [2]:
from collections import OrderedDict
# 建立一個 OrderedDict
d = OrderedDict()
d['first'] = 1
d['second'] = 2
d['third'] = 3

#
for key in d:
    print(key, d[key])

# Output:
# first 1
# second 2
# third 3

first 1
second 2
third 3


3. heapq

>- heapq模組實現了堆數據結構，也稱為優先隊列。

In [3]:
import heapq
# 建立
h = []
heapq.heappush(h, (5, 'AAA'))
heapq.heappush(h, (7, 'BBB'))
heapq.heappush(h, (1, 'CCC'))
heapq.heappush(h, (3, 'DDD'))
# 取出
print(heapq.heappop(h)) 
print(h)
# 再一次取出
print(heapq.heappop(h)) 
print(h)

(1, 'CCC')
[(3, 'DDD'), (7, 'BBB'), (5, 'AAA')]
(3, 'DDD')
[(5, 'AAA'), (7, 'BBB')]


>- 是一種提供 heap queue 演算法（priority queue 演算法）的庫，可以用於尋找和排序列表中的最小元素。

In [4]:
# 再做一個範例，把 list 轉換成 heap，並且輸出
# 建立一個 list
heap = [3, 1, 4, 1, 5, 9, 2, 6]
# 把 list 轉換成 heap
heapq.heapify(heap)
# 輸出，可以看到已經是 heap 的結構，但是不是排序好的
print(heap) 

[1, 1, 2, 3, 5, 9, 4, 6]


>- deque 提供了一個雙端隊列，可以從頭/尾兩端添加或刪除元素。

In [5]:
from collections import deque
# 建立一個 deque
d = deque()
# 加入元素
d.append('1')
d.append('2')
d.append('3')
# 輸出，可以看到是一個 list
print(f'長度 = {len(d)}')  # 3
print(f'd[0] = {d[0]}')  # '1'
print(f'd[-1] = {d[-1]}')  # '3'
print(d)  # deque(['1', '2', '3'])

print('------------------') 
# 建立一個 deque，並且指定元素
d = deque(range(5))
print(d)
print(f'長度 = {len(d)}')  # 5
# 移除元素，移除左邊的元素
d.popleft()  # '0'
print(d)
# 移除元素，移除右邊的元素
d.pop()  # '4'
print(d)  # deque([1, 2, 3])


長度 = 3
d[0] = 1
d[-1] = 3
deque(['1', '2', '3'])
------------------
deque([0, 1, 2, 3, 4])
長度 = 5
deque([1, 2, 3, 4])
deque([1, 2, 3])


# 其他高階容器

4. NumPy

>- NumPy是一個用於科學計算的庫，它提供了一個高效的多維數組對象 ndarray。

In [6]:
import numpy as np
# 建立一個 ndarray
a = np.array([1, 2, 3])
print(a)  # array([1, 2, 3])

# 建立一個 ndarray
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
[1 2 3]
[[1 2 3]
 [4 5 6]]


5. Pandas DataFrame

>- DataFrame 是 Pandas 庫中的二維表格數據結構，其中的列可以是不同的類型（int，float，str等）。

In [7]:
import pandas as pd
#
data = {'Name': ['Tom', 'Nick', 'John'], 'Age': [20, 21, 19]}
df = pd.DataFrame(data)
#
print(df)

# Output:
#   Name  Age
# 0  Tom   20
# 1 Nick   21
# 2 John   19


   Name  Age
0   Tom   20
1  Nick   21
2  John   19


---END---